# Generated by Django 3.2.3 on 2021-11-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211120_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='external_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='insta_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
