# Generated by Django 3.2.3 on 2021-11-26 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_user_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 26, 8, 29, 26, 883704, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
