# Generated by Django 3.2.3 on 2021-11-26 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 26, 9, 39, 37, 908805, tzinfo=utc)),
        ),
    ]
