# Generated by Django 3.2.3 on 2021-11-26 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_verificationtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
