# Generated by Django 3.2.3 on 2021-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_cover_photo',
            field=models.ImageField(upload_to='images/{user.id}'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(upload_to='music/{user.id}'),
        ),
    ]
