# Generated by Django 3.2.3 on 2021-11-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211119_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_cover_photo',
            field=models.ImageField(upload_to='images/{User.id}'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(upload_to='music/{User.id}'),
        ),
    ]
