# Generated by Django 3.2.3 on 2021-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211119_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_cover_photo',
            field=models.ImageField(upload_to='images/<django.db.models.query_utils.DeferredAttribute object at 0x000001BD1A75EFA0>'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(upload_to='music/<django.db.models.query_utils.DeferredAttribute object at 0x000001BD1A75EFA0>'),
        ),
    ]
