# Generated by Django 3.2.3 on 2021-11-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211119_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_cover_photo',
            field=models.ImageField(upload_to='images/<function Music.user_directory_path at 0x00000160B5E124C0>'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(upload_to='music/<function Music.user_directory_path at 0x00000160B5E124C0>'),
        ),
    ]
