# Generated by Django 3.2.3 on 2021-11-19 19:38

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211119_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_cover_photo',
            field=models.ImageField(upload_to=home.models.Music.music_cover_photo_directory_path),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(upload_to=home.models.Music.music_file_directory_path),
        ),
    ]
